---
plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "pkg/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"

# Style preferences
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

# Layout preferences
Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - "^\\s*#"
    - "https?://"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

# Metrics
Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"
    - "Rakefile"

# Naming
Naming/FileName:
  Exclude:
    - "Gemfile"
    - "Rakefile"

# Minitest-specific
Minitest/MultipleAssertions:
  Max: 10

# Gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false
